import React from 'react'
import PageTransition from '../component/PageTransition'

export const metadata = {
    title: 'Farrel Portfolio | Contact Page',
    description: 'Generated by create next app',
  }

const Contact = () => {
  return (
    <>
    <PageTransition/>
    <div>Contact</div>
    </>
  )
}

export default Contact