import React from 'react'

export const metadata = {
    title: 'Farrel Portfolio | About Page',
    description: 'Generated by create next app',
  }
const About = () => {
      
  return (
    <>
    <div>About</div>
    </>
  )
}

export default About