import React from 'react'
import About from '../component/About'
import Skills from './Skills'
import PageTransition from '../component/PageTransition'
export const metadata = {
    title: 'Farrel Portfolio | About Page',
    description: 'Generated by create next app',
  }
const AboutPage = () => {
      
  return (
    <>
    <PageTransition/>
    <div className='px-10'>
    <About/>
    <Skills/>
    </div>
    </>
  )
}

export default AboutPage