import React from 'react'

import PageTransition from '../component/PageTransition';
import ProjectComponent from './ProjectComponent';

export const metadata = {
  title: 'Farrel Portfolio | Projects Page',
  description: 'Generated by create next app',
}

const Projects = () => {
  return (
    <>
      <PageTransition />
      <div className='flex justify-center'>
        <div className="container">
          <div className="w-full px-4">
            <div className="max-w-xl mx-auto text-center my-16">
              <h2 className="font-bold text-3xl mb-2 text-dark text-center dark:text-light">Latest <span className='text-primary'>Project</span></h2>
              <div className="mb-16">
              </div>
            </div>
          </div>
          <ProjectComponent />
        </div>
      </div>
    </>
  )
}

export default Projects