import Hero from './component/Hero'
import Layout from './component/Layout'
import Head from 'next/head'

export const metadata = {
  title: 'Farrel Portfolio | Homepage',
  description: 'Generated by create next app',
}

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Farrel Portfolio | Homepage</title>
      </Head>
      <main className='flex items-start w-full h-full'>
          <Hero/>
      </main>
    </>
  )
}
